on:
  workflow_call:

  workflow_dispatch:

jobs:
  job:

    runs-on: ubuntu-latest

    steps:

      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Print repo's origin URL
        run: git config --get remote.origin.url
        shell: bash
